const express = require('express');
const connectDB = require('./config/db');
const app = express();
connectDB();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.set('view engine', 'ejs');
app.use('/inventory', require('./routes/inventory'));
app.get('/', (req, res) => res.redirect('/inventory/dashboard'));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`StockSense running on http://localhost:${PORT}`));
